server:
  port: 8005
  servlet:
    context-path: /
spring:
  application:   #定义服务名称
    name: web_consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: web_consumer         #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
