server:
  port: 8000
  servlet:
    context-path: /
spring:
  #application:   #定义服务名称
  #name: web_consumer
  resources:
    static-locations: classpath:/static/  #配置静态资源路径
  thymeleaf:
    cache: false #禁用模板缓存
    check-template-location: true #检测模板是否存在
    content-type: text/html #参数的值
    enabled: true #启动MVC视图分辨率
    prefix: classpath:/templates/ #模板前缀
    suffix: .html #模板后缀
    mode: LEGACYHTML5
  devtools: 
    restart:
     enabled: false


ribbon:
  eureka:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: web_consumer         #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
    
